@echo off
echo Closing current application...
taskkill /IM "All_in_One_v1.7.4.exe" /F
timeout /t 2 /nobreak

echo Downloading new version...
gdown "https://drive.google.com/uc?id=16j3qEERVKG0fMI9iUZBkwKvLSj-MzJSx" -O "All_in_One_v1.7.4.exe"

echo Starting new version...
start All_in_One_v1.7.4.exe

echo Cleaning up...
del "%~f0"
