@echo off
echo Closing current application...
taskkill /IM "All_in_One_v1.7.3.exe" /F
timeout /t 2 /nobreak

echo Downloading new version...
gdown "https://drive.google.com/uc?id=1yftvZdaSYL0Vrq2Vuqapf3jQSqxK-bFc" -O "All_in_One_v1.7.4.exe"

echo Starting new version...
start All_in_One_v1.7.4.exe

echo Cleaning up...
del "%~f0"
